export const SET_LOADING = "SET_LOADING";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const SET_USER = "SET_USER";

export const FETCH_COLLECTIONS_SUCCESS = "FETCH_COLLECTIONS_SUCCESS";
export const FETCH_COLLECTIONS_ERROR = "FETCH_COLLECTIONS_ERROR";
export const FETCH_SINGLE_COLLECTION_SUCCESS = "FETCH_COLLECTION_SUCCESS";
export const FETCH_SINGLE_COLLECTION_ERROR = "FETCH_COLLECTION_ERROR";

export const CREATE_COLLECTION_SUCCESS = "CREATE_COLLECTION_SUCCESS";
export const CREATE_COLLECTION_ERROR = "CREATE_COLLECTION_ERROR";
export const DELETE_COLLECTION_SUCCESS = "DELETE_COLLECTION_SUCCESS";
export const DELETE_COLLECTION_ERROR = "DELETE_COLLECTION_ERROR";

export const OPEN_ALERT = "OPEN_ALERT";
